video: Kconfig: Select FB_MODE_HELPERS for FB_FSL_DCU
Building FB_FSL_DCU without FB_MODE_HELPERS causes the following link
error to occur:

drivers/built-in.o: In function `fsl_dcu_probe':
:(.text+0x1f0e0): undefined reference to `fb_videomode_from_videomode'

Signed-off-by: Anthony Felice <tony.felice@timesys.com>